version: "3"

services:
  frontend:
    build:
      context: ./frontend
    image: trains-frontend
    container_name: trains-frontend
    ports:
      - "3000:80"
  backend:
    build:
      context: ./backend
    image: trains-backend
    container_name: trains-backend
    environment:
      - "REDIS_HOST=redis"
  redis:
    image: redis:3.2-alpine
    container_name: trains-redis
    ports:
      - "6379:6379"

